<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: ea114a63-1364-4ba5-9af5-b9105a8675da
 * Migration local datetime: 2024-06-15 21:21:09.283968
 * Migration UTC datetime: 2024-06-16 04:21:09.283968
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2024061521210928 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('leads', function (Blueprint $table) {
            $table->string('lead_time')->nullable(true)->after('declined');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('leads', function (Blueprint $table) {
            $table->dropColumn('lead_time');
        });
    }
}
