<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: ee75822d-518c-495e-b4fe-5f5602b16fc6
 * Migration local datetime: 2024-06-17 19:11:57.173972
 * Migration UTC datetime: 2024-06-18 02:11:57.173972
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2024061719115717 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->renameColumn('is_running', 'processed');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->renameColumn('processed', 'is_running');
        });
    }
}
