<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 5b1d2423-da7e-4596-8d59-76d92745756b
 * Migration local datetime: 2024-06-16 13:26:18.363342
 * Migration UTC datetime: 2024-06-16 20:26:18.363342
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2024061613261836 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('leads', function (Blueprint $table) {
            $table->string('card_month')->after('ip')->change();
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->string('card_year')->after('card_month')->change();
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->string('card_number')->after('card_year')->change();
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->integer('card_cvv')->after('card_number')->change();
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->dateTime('lead_time')->nullable(true)->after('declined')->change();
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->text('lead_url')->nullable(true)->after('lead_time');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->string('aff_id')->nullable(true)->after('lead_url');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->string('pub')->nullable(true)->after('aff_id');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->string('click_id')->nullable(true)->after('pub');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->text('c1')->nullable(true)->after('click_id');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->text('c2')->nullable(true)->after('c1');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->text('c3')->nullable(true)->after('c2');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('leads', function (Blueprint $table) {
            $table->dropColumn('c3');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->dropColumn('c2');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->dropColumn('c1');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->dropColumn('click_id');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->dropColumn('pub');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->dropColumn('aff_id');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->dropColumn('lead_url');
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->string('lead_time')->nullable(true)->after('declined')->change();
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->integer('card_cvv')->nullable(true)->after('card_number')->change();
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->string('card_number')->nullable(true)->after('card_year')->change();
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->string('card_year')->nullable(true)->after('card_month')->change();
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->string('card_month')->nullable(true)->after('ip')->change();
        });
    }
}
