<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: a4cf55dd-1cb7-44b0-bc8f-9d66b67707eb
 * Migration local datetime: 2024-06-15 20:30:53.487295
 * Migration UTC datetime: 2024-06-16 03:30:53.487295
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2024061520305348 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('log_files', function (Blueprint $table) {
            $table->json('data')->nullable(true)->after('updated_at')->change();
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('log_files', function (Blueprint $table) {
            $table->json('data')->nullable(true)->after('updated_at')->change();
        });
    }
}
