<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: c5bcbdc3-d10b-463f-900e-1699d8fca77d
 * Migration local datetime: 2024-06-15 20:18:02.031866
 * Migration UTC datetime: 2024-06-16 03:18:02.031866
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2024061520180203 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('leads', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->bigInteger('log_file_id')->nullable(true)->unsigned();
            $table->string('first_name')->nullable(true);
            $table->string('last_name')->nullable(true);
            $table->string('email')->nullable(true);
            $table->text('address_1')->nullable(true);
            $table->text('address_2')->nullable(true);
            $table->string('city')->nullable(true);
            $table->string('state')->nullable(true);
            $table->smallInteger('zip')->nullable(true);
            $table->string('country')->nullable(true);
            $table->string('ip')->nullable(true);
            $table->string('card_month')->nullable(true);
            $table->string('card_year')->nullable(true);
            $table->string('card_number')->nullable(true);
            $table->integer('card_cvv')->nullable(true);
            $table->boolean('declined')->nullable(true)->default(0);
        });
        Schema::table('leads', function (Blueprint $table) {
            $table->foreign('log_file_id')->references('id')->on('log_files');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('leads')) {
            Schema::table('leads', function (Blueprint $table) {
                $table->dropForeign(['log_file_id']);
            });
        }
        Schema::dropIfExists('leads');
    }
}
