<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: eea3dfd1-7471-4e96-9bdb-8ebbf916da8c
 * Migration local datetime: 2024-06-15 21:09:52.714190
 * Migration UTC datetime: 2024-06-16 04:09:52.714190
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2024061521095271 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('leads', function (Blueprint $table) {
            $table->string('phone')->nullable(true)->after('email');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('leads', function (Blueprint $table) {
            $table->dropColumn('phone');
        });
    }
}
