<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 206f3371-6f3a-4cbf-a718-90d15616a192
 * Migration local datetime: 2024-06-17 16:06:00.894142
 * Migration UTC datetime: 2024-06-17 23:06:00.894142
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2024061716060089 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('lead2_externals', function (Blueprint $table) {
            $table->bigInteger('id')->autoIncrement()->unsigned();
            $table->timestamp('created_at')->nullable(true);
            $table->timestamp('updated_at')->nullable(true);
            $table->bigInteger('lead_id')->unsigned();
            $table->dateTime('scheduled_time')->nullable(true);
            $table->string('external_service')->nullable(true);
            $table->boolean('is_running')->nullable(true)->default(0);
            $table->json('response')->nullable(true);
            $table->json('request')->nullable(true);
            $table->dateTime('finished')->nullable(true);
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->foreign('lead_id')->references('id')->on('leads');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        if (Schema::hasTable('lead2_externals')) {
            Schema::table('lead2_externals', function (Blueprint $table) {
                $table->dropForeign(['lead_id']);
            });
        }
        Schema::dropIfExists('lead2_externals');
    }
}
