<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: d5c4d3f2-a885-4256-94fc-6a1ecbc0fadd
 * Migration local datetime: 2024-06-17 18:25:08.987752
 * Migration UTC datetime: 2024-06-18 01:25:08.987752
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2024061718250898 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->bigInteger('lead_id')->unsigned()->after('updated_at')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->dateTime('scheduled_time')->nullable(true)->after('lead_id')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->string('external_service')->nullable(true)->after('scheduled_time')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->boolean('is_running')->nullable(true)->default(0)->after('external_service')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->json('response')->nullable(true)->after('is_running')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->json('request')->nullable(true)->after('response')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->dateTime('finished')->nullable(true)->after('request')->change();
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->dateTime('finished')->nullable(true)->after('request')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->json('request')->nullable(true)->after('response')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->json('response')->nullable(true)->after('is_running')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->boolean('is_running')->nullable(true)->default(0)->after('external_service')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->string('external_service')->nullable(true)->after('scheduled_time')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->dateTime('scheduled_time')->nullable(true)->after('lead_id')->change();
        });
        Schema::table('lead2_externals', function (Blueprint $table) {
            $table->bigInteger('lead_id')->unsigned()->after('updated_at')->change();
        });
    }
}
