<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: 785cb966-d475-4e49-b361-ad8d5effc573
 * Migration local datetime: 2024-06-15 19:27:35.036878
 * Migration UTC datetime: 2024-06-16 02:27:35.036878
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2024061519273503 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('log_files', function (Blueprint $table) {
            $table->json('data')->nullable(true)->after('updated_at');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('log_files', function (Blueprint $table) {
            $table->dropColumn('data');
        });
    }
}
