<?php
/* 
 * Migrations generated by: Skipper (http://www.skipper18.com)
 * Migration id: b9d2aded-af0a-4802-9cfc-99b0b4837a21
 * Migration local datetime: 2024-06-15 20:20:23.790757
 * Migration UTC datetime: 2024-06-16 03:20:23.790757
 */ 

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SkipperMigrations2024061520202379 extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('log_files', function (Blueprint $table) {
            $table->boolean('leads_exported')->nullable(true)->default(0)->after('total_leads');
        });
    }
    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('log_files', function (Blueprint $table) {
            $table->dropColumn('leads_exported');
        });
    }
}
