<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractJob
* @package App\Models\AbstractModels
*
* @property bigInteger $id
* @property string $queue
* @property longText $payload
* @property tinyInteger $attempts
* @property integer $reserved_at
* @property integer $available_at
* @property integer $created_at
*/ 
abstract class AbstractJob extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'jobs';
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'queue' => 'string',
        'payload' => 'string',
        'attempts' => 'integer',
        'reserved_at' => 'integer',
        'available_at' => 'integer',
        'created_at' => 'integer'
    ];
}
