<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractSession
* @package App\Models\AbstractModels
*
* @property string $id
* @property bigInteger $user_id
* @property string $ip_address
* @property text $user_agent
* @property longText $payload
* @property integer $last_activity
*/ 
abstract class AbstractSession extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'sessions';
    
    /**  
     * Primary key type.
     * 
     * @var string
     */
    protected $keyType = 'string';
    
    /**  
     * Primary key is non-autoincrementing.
     * 
     * @var bool
     */
    public $incrementing = false;
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'string',
        'user_id' => 'integer',
        'ip_address' => 'string',
        'user_agent' => 'string',
        'payload' => 'string',
        'last_activity' => 'integer'
    ];
}
