<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractLead
* @package App\Models\AbstractModels
*
* @property bigInteger $id
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property bigInteger $log_file_id
* @property string $first_name
* @property string $last_name
* @property string $email
* @property string $phone
* @property text $address_1
* @property text $address_2
* @property string $city
* @property string $state
* @property string $zip
* @property string $country
* @property string $ip
* @property string $card_month
* @property string $card_year
* @property string $card_number
* @property integer $card_cvv
* @property boolean $declined
* @property string $lead_time
* @property \App\Models\LogFile|null $logFile
*/ 
abstract class AbstractLead extends Model
{
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['declined' => 0];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'log_file_id' => 'integer',
        'first_name' => 'string',
        'last_name' => 'string',
        'email' => 'string',
        'phone' => 'string',
        'address_1' => 'string',
        'address_2' => 'string',
        'city' => 'string',
        'state' => 'string',
        'zip' => 'string',
        'country' => 'string',
        'ip' => 'string',
        'card_month' => 'string',
        'card_year' => 'string',
        'card_number' => 'string',
        'card_cvv' => 'integer',
        'declined' => 'boolean',
        'lead_time' => 'string'
    ];
    
    public function logFile()
    {
        return $this->belongsTo('\App\Models\LogFile', 'log_file_id', 'id');
    }
}
